# Pre-commit hooks for Fugatto Audio Lab
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # 10MB limit for audio samples
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]

  # Advanced security and AI-specific hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*\.lock$
  
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
  
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
  
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]
        additional_dependencies: [tomli]
  
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [--tb=short, -x]
      
      - id: model-size-check
        name: check-model-file-sizes
        entry: python
        language: system
        args: [-c, "import os; import sys; max_size=100*1024*1024; files=[f for f in sys.argv[1:] if f.endswith(('.pt', '.pth', '.ckpt', '.safetensors'))]; oversized=[f for f in files if os.path.exists(f) and os.path.getsize(f) > max_size]; sys.exit(1) if oversized else sys.exit(0)"]
        files: \.(pt|pth|ckpt|safetensors)$
      
      - id: audio-quality-check
        name: check-audio-sample-quality
        entry: python
        language: system
        args: [-c, "import sys; import soundfile as sf; [sf.info(f) for f in sys.argv[1:] if f.endswith(('.wav', '.flac', '.mp3'))]"]
        files: \.(wav|flac|mp3)$
        pass_filenames: true